{{- if .Values.app2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: argo-service-2
  namespace: {{ .Values.app2.namespace}}
spec:
  selector:
    app: {{ .Values.app2.label }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app2.port }}
{{- end }}
