app1:
  enabled: true
  name: argo-deployment
  label: argo
  image: 487383300987.dkr.ecr.us-east-1.amazonaws.com/eks
  port: 9000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

app2:
  enabled: true
  name: argo-deployment-2
  label: argo-2
  image: 487383300987.dkr.ecr.us-east-1.amazonaws.com/test
  port: 80
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  hostname: vijay.klizos.com
  certificateArn: arn:aws:acm:us-east-1:487383300987:certificate/8dd54571-d95c-4cbe-b004-79d8a73985bc
